name: ci

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 检查构建机器上的存储库。
      -
        name: Checkout
        uses: actions/checkout@v3
    # 通过Actions的配置登录 Docker Hub, 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    # 使用 Docker Setup Buildx 操作创建 BuildKit builder instance实例。
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    # 使用 Build and push Docker images, build 和 push 镜像到 Docker Hub 上
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          # the build context
          context: ./go/docker-gs-ping/.
          # filepath to the Dockerfile.
          file: ./go/docker-gs-ping/Dockerfile
          # tells the action to upload the image to a registry after building it.
          push: true 
          # tags that specify where to push the image.
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
